"""Create initial schema with Job, Skill, JobSkill, PipelineRun

Revision ID: be03e32c2dc0
Revises: 
Create Date: 2026-06-29 13:34:00.426516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be03e32c2dc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_site', 'source_id', name='uq_job_source')
    )
    op.create_index('idx_jobs_posted_date_desc', 'jobs', [sa.literal_column('posted_date DESC')], unique=False)
    op.create_index('idx_jobs_salary_range', 'jobs', ['salary_min', 'salary_max'], unique=False)
    op.create_index('idx_jobs_scraped_date_desc', 'jobs', [sa.literal_column('scraped_date DESC')], unique=False)
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.create_index(op.f('ix_jobs_experience_level'), 'jobs', ['experience_level'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_is_deleted'), 'jobs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_jobs_posted_date'), 'jobs', ['posted_date'], unique=False)
    op.create_index(op.f('ix_jobs_remote_type'), 'jobs', ['remote_type'], unique=False)
    op.create_index(op.f('ix_jobs_salary_max'), 'jobs', ['salary_max'], unique=False)
    op.create_index(op.f('ix_jobs_salary_min'), 'jobs', ['salary_min'], unique=False)
    op.create_index(op.f('ix_jobs_scraped_date'), 'jobs', ['scraped_date'], unique=False)
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_jobs_source_site'), 'jobs', ['source_site'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'running'"), nullable=False),
    sa.Column('records_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_started_at_desc', 'pipeline_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_pipeline_runs_source_site'), 'pipeline_runs', ['source_site'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_started_at'), 'pipeline_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_name_lower', 'skills', [sa.literal_column('lower(name)')], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index('idx_skills_name_lower', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_started_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_source_site'), table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_started_at_desc', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_site'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scraped_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_salary_min'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_salary_max'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_posted_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_deleted'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_experience_level'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_index('idx_jobs_scraped_date_desc', table_name='jobs')
    op.drop_index('idx_jobs_salary_range', table_name='jobs')
    op.drop_index('idx_jobs_posted_date_desc', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
